#ifndef MafMwSpiLog_1_h_
#define MafMwSpiLog_1_h_

#include <stdint.h>
#include <MafMgmtSpiInterface_1.h>
#include <MafMgmtSpiCommon.h>

/**
 * Log interface.
 *
 * @file MafMwSpiLog_1.h
 * @ingroup MafMwSpi
 *
 * The SPI basic function is to provide log information to the MAF SA agent, implementing
 * the log service interface. The mapping of log information to physical logs are
 * determined by the agent implementation.
 * The log service can be used to write high-level cluster-significant information
 * suited primarily for network administrators or system administrators.
 * Thus, the log service does not need to support low-level implementation centric logging.
 *
 */


/**
 * The system is unusable.
 */
#define MW_SA_LOG_SEV_EMERGENCY	0
/**
 * Action must be taken immediately.
 */
#define MW_SA_LOG_SEV_ALERT		1
/**
 * Critical condition.
 */
#define MW_SA_LOG_SEV_CRITICAL	2
/**
 * Error condition.
 */
#define MW_SA_LOG_SEV_ERROR		3
/**
 * Warning condition.
 */
#define MW_SA_LOG_SEV_WARNING	4
/**
 * Normal but significant condition.
 */
#define MW_SA_LOG_SEV_NOTICE	5
/**
 * Informative message.
 */
#define MW_SA_LOG_SEV_INFO		6
/**
 * The MwSpiSeverityT type is used to specify the severity level of a log record.
 * The severity levels are as follows:
 * @li EMERGENCY - The system is unusable.
 * @li ALERT - Action must be taken immediately.
 * @li CRITICAL - Critical condition.
 * @li ERROR - Error condition.
 * @li WARNING - Warning condition.
 * @li NOTICE - Normal but significant condition.
 * @li INFO - Informative message.
 *
 * The numerical codes are according to IETF RFC 5424, the Syslog Protocol.
 */
#ifndef MwSpiSeverityT_typedef
#define MwSpiSeverityT_typedef
typedef uint16_t MwSpiSeverityT;
#endif

/**
 * The MwSpiFacilityT type is specifying which type of log file (audit log, daemon log, etc) the messages will be written to.
 *
 * The numerical codes are according to IETF RFC 5424, the Syslog Protocol and extended with:
 * 100	alarm log record generated by Fault Management
 * 101	alert log record generated by Fault Management
 */
#ifndef MwSpiFacilityT_typedef
#define MwSpiFacilityT_typedef
typedef uint16_t MwSpiFacilityT;
#endif

/**
 * Log interface.
 * The interface supports write operations to the log.
 */
typedef struct MafMwSpiLog_1 {
    /**
     * Common interface description.
     * The "base class" for this interface. Contains component name, interface name and interface version.
     */
    MafMgmtSpiInterface_1T base;
    /**
     * Writes a new entry to a log, the facility parameter decides in which log to write.
     *
     * The log format can differ per facility but when writing to facility 100 or 101, the alarm log
     * and the alert log, the client has full responsibility for the log format why the
     * middleware SA must not write any extra information to the log or in other way modify the
     * received data buffer.
     * The SA shall make the alarm log visible under the directory /FaultManagementLog/alarm/
     * relative to the NBI internal root.
     * The SA shall make the alert log visible under the directory /FaultManagementLog/alert/
     * relative to the NBI internal root.
     * The SA is responsible to create and maintain the produced log files in the directories.
     *
     *
     * @param[in] eventId Internationalization data. A number represents the event.
     * The parameter is not specified if the value is zero.
     *
     * @param[in] severity Severity level of the event.
     *
     * @param[in] facility The  facility  argument is used to specify what
     * type of program is logging the message.
     *
     * @param[in] databuffer Pointer to a null character terminated character buffer containing the new log data, that is
     * all printable ASCII characters.
     *
     * @return MafOk or MafFailure.
     */
    MafReturnT (*logWrite) (uint32_t eventId, MwSpiSeverityT severity, MwSpiFacilityT facility, const char* databuffer);
} MafMwSpiLog_1T;

#endif
